[package]
name    = "iced_picker"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.13"

[dev-dependencies]
iced_fonts = { version = "0.2.1", features = ["nerd"] }

[[example]]
name = "file_picker"
path = "src/examples/file_picker.rs"
